config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals do
    resources :months
    resources :weeks
	resources :days
  end

  root 'goals#index'

end

# Peters-MacBook-Pro:MeDoo petervarga$ rake routes
#                   Prefix Verb   URI Pattern                               Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                  devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                  devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                 devise/sessions#destroy
#            user_password POST   /users/password(.:format)                 devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)             devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)            devise/passwords#edit
#                          PATCH  /users/password(.:format)                 devise/passwords#update
#                          PUT    /users/password(.:format)                 devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                   devise/registrations#cancel
#        user_registration POST   /users(.:format)                          devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                  devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                     devise/registrations#edit
#                          PATCH  /users(.:format)                          devise/registrations#update
#                          PUT    /users(.:format)                          devise/registrations#update
#                          DELETE /users(.:format)                          devise/registrations#destroy
#              goal_months GET    /goals/:goal_id/months(.:format)          months#index
#                          POST   /goals/:goal_id/months(.:format)          months#create
#           new_goal_month GET    /goals/:goal_id/months/new(.:format)      months#new
#          edit_goal_month GET    /goals/:goal_id/months/:id/edit(.:format) months#edit
#               goal_month GET    /goals/:goal_id/months/:id(.:format)      months#show
#                          PATCH  /goals/:goal_id/months/:id(.:format)      months#update
#                          PUT    /goals/:goal_id/months/:id(.:format)      months#update
#                          DELETE /goals/:goal_id/months/:id(.:format)      months#destroy
#               goal_weeks GET    /goals/:goal_id/weeks(.:format)           weeks#index
#                          POST   /goals/:goal_id/weeks(.:format)           weeks#create
#            new_goal_week GET    /goals/:goal_id/weeks/new(.:format)       weeks#new
#           edit_goal_week GET    /goals/:goal_id/weeks/:id/edit(.:format)  weeks#edit
#                goal_week GET    /goals/:goal_id/weeks/:id(.:format)       weeks#show
#                          PATCH  /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          PUT    /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          DELETE /goals/:goal_id/weeks/:id(.:format)       weeks#destroy
#                goal_days GET    /goals/:goal_id/days(.:format)            days#index
#                          POST   /goals/:goal_id/days(.:format)            days#create
#             new_goal_day GET    /goals/:goal_id/days/new(.:format)        days#new
#            edit_goal_day GET    /goals/:goal_id/days/:id/edit(.:format)   days#edit
#                 goal_day GET    /goals/:goal_id/days/:id(.:format)        days#show
#                          PATCH  /goals/:goal_id/days/:id(.:format)        days#update
#                          PUT    /goals/:goal_id/days/:id(.:format)        days#update
#                          DELETE /goals/:goal_id/days/:id(.:format)        days#destroy
#                    goals GET    /goals(.:format)                          goals#index
#                          POST   /goals(.:format)                          goals#create
#                 new_goal GET    /goals/new(.:format)                      goals#new
#                edit_goal GET    /goals/:id/edit(.:format)                 goals#edit
#                     goal GET    /goals/:id(.:format)                      goals#show
#                          PATCH  /goals/:id(.:format)                      goals#update
#                          PUT    /goals/:id(.:format)                      goals#update
#                          DELETE /goals/:id(.:format)                      goals#destroy
#                     root GET    /                                         goals#index

app/models/week.rb
class Week < ActiveRecord::Base
  validates :weekly_goal_name, presence: true
  belongs_to :goals

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :load_master_goal, :load_date_info, :check_goal_owner

  def index
    # sql select all the sub-monthly-goals -> input from the monthly view
    @given_month_sub_goals = @master_goal.months.where(month_num:@month, year:@year)

    # sql select all the sub-weekly-goals -> input that was previously typed in This weekly view
    @month_week_goals = load_month_week_goals(@master_goal, @year, @month)

    # Creating the "framework" for displaying the @weekly_goals on page (sections' descriptions + week_num provided)
    @weeks_array = create_weeks_array(@year, @month)

    # Creating variables for < > selection of the month, making sure that there is 1 after 12
    @next_month = next_month(@month)
    @previous_month = previous_month(@month)
  end

  def new
    @week_num = params["week_num"]
  end

  def create
    @new_week_goal = @master_goal.weeks.new(year: params[:year], week_num: params[:week_num], weekly_goal_name: params[:new_weekly_todo])
    if @new_week_goal.save
      redirect_to goal_weeks_path(@master_goal,month:@month,year:params[:year]), notice: 'Weekly goal was created'
    else
      redirect_to goal_weeks_path(@master_goal,month:@month,year:params[:year]), notice: 'Try again! Weekly goal was NOT created'
    end
  end

  def edit
    @week_goal = Week.find(params[:id])    
  end

  def update
    @week_goal = Week.find(params[:id])
    @week_goal.update(week_goal_params)
    redirect_to goal_weeks_path(@master_goal,month:@month)
  end

  def destroy
    @week_goal = Week.find(params[:id])
    @week_goal.destroy
    redirect_to goal_weeks_path(@master_goal,month:@month)
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :description)
  end

  def load_master_goal
    @master_goal = Goal.find(params[:goal_id])
  end

  def load_date_info
    if params["month"] != nil
      @month = params["month"].to_i
    else
      @month = Date.today.month
    end

    if params["year"] != nil
      @year = params["year"].to_i
    else
      @year = Date.today.year
    end
  end

  def previous_month(month)
     if month-1 > 0
      previous_month = month-1
    else
      previous_month = 12
    end
    
  end

  def next_month(month)
    if month+1 < 13
      next_month = month+1
    else
      next_month = 1
    end
  end

  def create_weeks_array(year, month)
    weeks_array = []
    month_begining_day = Date.new(year, month, 1)
    month_ending_day = month_begining_day.at_end_of_month
    month_begining_week = month_begining_day.strftime("%V").to_i
    month_ending_week = month_ending_day.strftime("%V").to_i
    week_begining_day = month_begining_day.beginning_of_week
    week_ending_day = week_begining_day.end_of_week
    week = month_begining_week
    until week == month_ending_week
      weeks_array.push({year:year, month:month, week_num: week, week_dates:"#{Date::MONTHNAMES[week_begining_day.month]}#{week_begining_day.day}-#{Date::MONTHNAMES[week_ending_day.month]}#{week_ending_day.day}"})
      week_begining_day += 7
      week_ending_day += 7
      week = week_begining_day.strftime("%V").to_i
    end

    if month_ending_week>month_begining_week
      weeks_array.push({year:year, month:month,  week_num: week, week_dates:"#{Date::MONTHNAMES[week_begining_day.month]}#{week_begining_day.day}-#{Date::MONTHNAMES[week_ending_day.month]}#{week_ending_day.day}"})
    else
      weeks_array.push({year:(year.to_i+1), month:1, week_num: week, week_dates:"#{Date::MONTHNAMES[week_begining_day.month]}#{week_begining_day.day}-#{Date::MONTHNAMES[week_ending_day.month]}#{week_ending_day.day}"})    
    end
    return weeks_array
  end

  # Selecting only the week_num(s) that belong to given month. 
  def load_month_week_goals(master_goal, year, month)  
    week_array = create_weeks_array(year,month)
    if week_array.first[:week_num]<week_array.last[:week_num]
      month_week_goals = master_goal.weeks.where(week_num:week_array.first[:week_num]..week_array.last[:week_num], year:year)
    else
      # Resolving also potential Dec issue where last week is #1
      month_week_goals = master_goal.weeks.where( '(week_num >= ? AND year = ?) OR (week_num = 1 AND year = ? )', week_array.first[:week_num], year, year+1 )
    end
    return month_week_goals
  end

  def week_goal_params
    params.require(:week).permit(:weekly_goal_name, :year ,:week_num)
  end

end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/edit.html.erb
<% content_for :body_type do%>
  goalsedit
<% end %>

<div class="col-md-4 col-sm-4 col-xs-6 col-md-offset-4 col-sm-offset-4">
  <h3>Edit your goal</h3>
  <%= bootstrap_form_for([@master_goal, @week_goal]) do |f| %>
    <%= label_tag(:weekly_goal_name, "Current goal") %>
    <%= f.text_field :weekly_goal_name, hide_label: true  %></br>
    <%= label_tag(:week_num, "Week") %>
    <%= f.text_field :week_num, hide_label: true  %></br>
    <%= label_tag(:year, "Year") %>
    <%= f.text_field :year, hide_label: true  %></br>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <%end%>
  <%= link_to "Remove", goal_week_path(@master_goal, @week_goal, month:@month), method: 'delete', :confirm => 'Are you sure?'%>
</div>

app/views/weeks/index.html.erb
<% content_for :body_type do%>
weekindex<% end %>
<div class ="weekbanner">
  <%= link_to("All goals", root_path) %> <br>
  <%= link_to("#{@year} overview", goal_months_path(@master_goal, year:@year)) %>
</div>

<div class ="weekshow">
  <hr>
  <h1 id="weeksheader">Monthly Sub-Goals for:</h1>

  <%= link_to('<---', goal_weeks_path(@master_goal,month:@month,year:@year.to_i-1))%>
    <%=@year%>
  <%= link_to('--->', goal_weeks_path(@master_goal,month:@month,year:@year.to_i+1))%>
  <br>
  <%= link_to('<---', goal_weeks_path(@master_goal, month:@previous_month, year:@year))%>
    <%=Date::MONTHNAMES[@month]%>
  <%= link_to('--->', goal_weeks_path(@master_goal, month:@next_month, year:@year))%>
  <hr>


  <ul id="weeksullist">
    <% @given_month_sub_goals.each do |given_month_sub_goal| %>
      <li><%=given_month_sub_goal.month_goal_name%></li>
    <% end %>
  </ul>
<hr>
</div>


<% @weeks_array.each do |week| %>
<div class ="weeklist">

  <h2 id="weekstitle"><%= link_to("#{week[:week_dates]} (week#: #{week[:week_num]})", goal_days_path(@master_goal,week:week[:week_num],year:week[:year]))%></h2>


  <% if @month_week_goals.where(week_num: week[:week_num], year: week[:year]) != nil %>
    <% @month_week_goals.where(week_num: week[:week_num], year: week[:year]).each do |goal| %>
      <%= goal.weekly_goal_name %> <%= link_to "Edit", edit_goal_week_path(@master_goal, goal, month:@month)%><br>
    <% end %>
  <% end %>
  <%= link_to("Create New Weekly Goal", new_goal_week_path(@master_goal, week_num:week[:week_num],year:week[:year])) %>
  <hr>
<% end %>
</div>

app/views/weeks/new.html.erb
<% content_for :body_type do%>
weeknew<% end %>
<form action="<%=goal_weeks_path(@master_goal,month:@month,week_num:@week_num, year:@year)%>" method="post">
  <%= token_tag form_authenticity_token %>

 <div id ="newweekly"> New weekly goal:</div> 

<input autofocus type="text" placeholder="What do you want to accomplish!" name="new_weekly_todo" id ="weeklyinput">

<div class="newbuttonarea">
<input type="submit" value="Submit" id ="newbutton"/>
</div>
 
</form>