config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals do
    resources :months
    resources :weeks
	resources :days
  end

  root 'goals#index'

end

# Peters-MacBook-Pro:MeDoo petervarga$ rake routes
#                   Prefix Verb   URI Pattern                               Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                  devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                  devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                 devise/sessions#destroy
#            user_password POST   /users/password(.:format)                 devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)             devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)            devise/passwords#edit
#                          PATCH  /users/password(.:format)                 devise/passwords#update
#                          PUT    /users/password(.:format)                 devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                   devise/registrations#cancel
#        user_registration POST   /users(.:format)                          devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                  devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                     devise/registrations#edit
#                          PATCH  /users(.:format)                          devise/registrations#update
#                          PUT    /users(.:format)                          devise/registrations#update
#                          DELETE /users(.:format)                          devise/registrations#destroy
#              goal_months GET    /goals/:goal_id/months(.:format)          months#index
#                          POST   /goals/:goal_id/months(.:format)          months#create
#           new_goal_month GET    /goals/:goal_id/months/new(.:format)      months#new
#          edit_goal_month GET    /goals/:goal_id/months/:id/edit(.:format) months#edit
#               goal_month GET    /goals/:goal_id/months/:id(.:format)      months#show
#                          PATCH  /goals/:goal_id/months/:id(.:format)      months#update
#                          PUT    /goals/:goal_id/months/:id(.:format)      months#update
#                          DELETE /goals/:goal_id/months/:id(.:format)      months#destroy
#               goal_weeks GET    /goals/:goal_id/weeks(.:format)           weeks#index
#                          POST   /goals/:goal_id/weeks(.:format)           weeks#create
#            new_goal_week GET    /goals/:goal_id/weeks/new(.:format)       weeks#new
#           edit_goal_week GET    /goals/:goal_id/weeks/:id/edit(.:format)  weeks#edit
#                goal_week GET    /goals/:goal_id/weeks/:id(.:format)       weeks#show
#                          PATCH  /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          PUT    /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          DELETE /goals/:goal_id/weeks/:id(.:format)       weeks#destroy
#                goal_days GET    /goals/:goal_id/days(.:format)            days#index
#                          POST   /goals/:goal_id/days(.:format)            days#create
#             new_goal_day GET    /goals/:goal_id/days/new(.:format)        days#new
#            edit_goal_day GET    /goals/:goal_id/days/:id/edit(.:format)   days#edit
#                 goal_day GET    /goals/:goal_id/days/:id(.:format)        days#show
#                          PATCH  /goals/:goal_id/days/:id(.:format)        days#update
#                          PUT    /goals/:goal_id/days/:id(.:format)        days#update
#                          DELETE /goals/:goal_id/days/:id(.:format)        days#destroy
#                    goals GET    /goals(.:format)                          goals#index
#                          POST   /goals(.:format)                          goals#create
#                 new_goal GET    /goals/new(.:format)                      goals#new
#                edit_goal GET    /goals/:id/edit(.:format)                 goals#edit
#                     goal GET    /goals/:id(.:format)                      goals#show
#                          PATCH  /goals/:id(.:format)                      goals#update
#                          PUT    /goals/:id(.:format)                      goals#update
#                          DELETE /goals/:id(.:format)                      goals#destroy
#                     root GET    /                                         goals#index

app/models/month.rb
class Month < ActiveRecord::Base
  validates :month_goal_name, presence: true
  belongs_to :goal
  has_many :weeks

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController

  before_action :load_master_goal, :load_date_info, :check_goal_owner

  def index
    # sql select all the sub-monthly-goals -> -> input that was previously typed in This months view
    @monthly_goals = @master_goal.months.where(year:@year)
    @months_array = [{month_name:'January', month_num: 1},
                     {month_name:'February', month_num: 2},
                     {month_name:'March', month_num: 3},
                     {month_name:'April', month_num: 4},
                     {month_name:'May', month_num: 5},
                     {month_name:'Jun', month_num: 6},
                     {month_name:'July', month_num: 7},
                     {month_name:'August', month_num: 8},
                     {month_name:'September', month_num: 9},
                     {month_name:'October', month_num: 10},
                     {month_name:'November', month_num: 11},
                     {month_name:'December', month_num: 12},]
  end

  def new
    @month_num = params["month_num"]
  end

  def create    
    @month_goal = @master_goal.months.new(month_num: params[:month_num], month_goal_name: params[:new_monthly_todo], year:@year)
    if @month_goal.save
      redirect_to goal_months_path(@master_goal,year:@year), notice: 'monthly goal was created'
    else
      redirect_to goal_months_path(@master_goal,year:@year), notice: 'Goal was NOT created, try again'
    end
  end

  def edit
    @month_goal = Month.find(params[:id])
  end

  def update
    @month_goal = Month.find(params[:id])
    @month_goal.update(month_goal_params)
    redirect_to goal_months_path(@master_goal)
  end

  def destroy
    @month_goal = Month.find(params[:id])
    @month_goal.destroy
    redirect_to goal_months_path(@master_goal)
  end

  private

  def month_goal_params
    params.require(:month).permit(:month_goal_name, :year ,:month_num)
  end

  def load_master_goal
    @master_goal = Goal.find(params[:goal_id])
  end


  def load_date_info
    if params["year"] != nil
      @year = params["year"]
    else
      @year = Date.today.year
    end
  end

end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/months/edit.html.erb
<% content_for :body_type do%>
  goalsedit
<% end %>

<div class="col-md-4 col-sm-4 col-xs-6 col-md-offset-4 col-sm-offset-4">
  <h3>Edit your goal</h3>
  <%= bootstrap_form_for([@master_goal, @month_goal]) do |f| %>
    <%= label_tag(:month_goal_name, "Current goal") %>
    <%= f.text_field :month_goal_name, hide_label: true  %></br>
    <%= label_tag(:month_num, "Month") %>
    <%= f.text_field :month_num, hide_label: true  %></br>
    <%= label_tag(:year, "Year") %>
    <%= f.text_field :year, hide_label: true  %></br>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <%end%>
  <%= link_to "Remove", goal_month_path(@master_goal,@month_goal), method: 'delete', :confirm => 'Are you sure?'%>
</div>

app/views/months/index.html.erb
<% content_for :body_type do%>
monthsindex<% end %>

<br/>
<br/>
<br/>
<div class="monthindextext">

<h1>Goal: <u><%=@master_goal.name%></u></h1>
<h3>Details: <%=@master_goal.description%></h3>

</div>


<h1><%= link_to('<', goal_months_path(@master_goal,year:@year.to_i-1))%>
  <%=@year%>
<%= link_to('>', goal_months_path(@master_goal,year:@year.to_i+1))%></h1>

</h1>

<% @months_array.each do |month| %>
	<table class="monthtable" id="month_<%= month[:month_num] %>">
		<thead>
			<tr>
				<th><b><%= link_to(month[:month_name], goal_weeks_path(@master_goal,month:month[:month_num],year:@year))%></b></th>
			</tr>
		</thead>
	<div class="monthmenu" id="month_<%= month[:month_num] %>">
		<tbody>
			<tr>
  			<% @monthly_goals.where(month_num: month[:month_num], year:@year).each do |monthly_goal| %>
          <td id="monthlygoal">
            <%= monthly_goal.month_goal_name %>
            <%= link_to "Edit", edit_goal_month_path(@master_goal, monthly_goal)%> / <span>
            <%= link_to "Remove", goal_month_path(@master_goal, monthly_goal), method: 'delete'%></span>
          </td>
        </tr>
        <% end %>
        <td><%= link_to("+ New Monthly Goal", new_goal_month_path(@master_goal, month_num:month[:month_num], year:@year), class: "btn btn-primary") %></td>
      </tr>
<% end %>
	</tbody>
  </table>
</div>

app/views/months/new.html.erb
<% content_for :body_type do%>
monthsnew<% end %>

<div class="form-group">
	<div class="col-md-6">
		<form action="<%=goal_months_path(@master_goal,month_num:@month_num,year:@year)%>" method="post">
  		<%= token_tag form_authenticity_token %>
  			<h3 id="newmonthheader">New Goal For: <%= "#{Date::MONTHNAMES[@month_num.to_i]}, #{@year}" %></h3>
  				<input type="text" placeholder="Exercise 3 times a week, etc." name="new_monthly_todo" class="form-control">
<br />
  				<input type = "submit" id="monthsubmit">
	</div>
		</form>
</div>