config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals do
    resources :months
    resources :weeks
	resources :days
  end

  root 'goals#index'

end

# Peters-MacBook-Pro:MeDoo petervarga$ rake routes
#                   Prefix Verb   URI Pattern                               Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                  devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                  devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                 devise/sessions#destroy
#            user_password POST   /users/password(.:format)                 devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)             devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)            devise/passwords#edit
#                          PATCH  /users/password(.:format)                 devise/passwords#update
#                          PUT    /users/password(.:format)                 devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                   devise/registrations#cancel
#        user_registration POST   /users(.:format)                          devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                  devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                     devise/registrations#edit
#                          PATCH  /users(.:format)                          devise/registrations#update
#                          PUT    /users(.:format)                          devise/registrations#update
#                          DELETE /users(.:format)                          devise/registrations#destroy
#              goal_months GET    /goals/:goal_id/months(.:format)          months#index
#                          POST   /goals/:goal_id/months(.:format)          months#create
#           new_goal_month GET    /goals/:goal_id/months/new(.:format)      months#new
#          edit_goal_month GET    /goals/:goal_id/months/:id/edit(.:format) months#edit
#               goal_month GET    /goals/:goal_id/months/:id(.:format)      months#show
#                          PATCH  /goals/:goal_id/months/:id(.:format)      months#update
#                          PUT    /goals/:goal_id/months/:id(.:format)      months#update
#                          DELETE /goals/:goal_id/months/:id(.:format)      months#destroy
#               goal_weeks GET    /goals/:goal_id/weeks(.:format)           weeks#index
#                          POST   /goals/:goal_id/weeks(.:format)           weeks#create
#            new_goal_week GET    /goals/:goal_id/weeks/new(.:format)       weeks#new
#           edit_goal_week GET    /goals/:goal_id/weeks/:id/edit(.:format)  weeks#edit
#                goal_week GET    /goals/:goal_id/weeks/:id(.:format)       weeks#show
#                          PATCH  /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          PUT    /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          DELETE /goals/:goal_id/weeks/:id(.:format)       weeks#destroy
#                goal_days GET    /goals/:goal_id/days(.:format)            days#index
#                          POST   /goals/:goal_id/days(.:format)            days#create
#             new_goal_day GET    /goals/:goal_id/days/new(.:format)        days#new
#            edit_goal_day GET    /goals/:goal_id/days/:id/edit(.:format)   days#edit
#                 goal_day GET    /goals/:goal_id/days/:id(.:format)        days#show
#                          PATCH  /goals/:goal_id/days/:id(.:format)        days#update
#                          PUT    /goals/:goal_id/days/:id(.:format)        days#update
#                          DELETE /goals/:goal_id/days/:id(.:format)        days#destroy
#                    goals GET    /goals(.:format)                          goals#index
#                          POST   /goals(.:format)                          goals#create
#                 new_goal GET    /goals/new(.:format)                      goals#new
#                edit_goal GET    /goals/:id/edit(.:format)                 goals#edit
#                     goal GET    /goals/:id(.:format)                      goals#show
#                          PATCH  /goals/:id(.:format)                      goals#update
#                          PUT    /goals/:id(.:format)                      goals#update
#                          DELETE /goals/:id(.:format)                      goals#destroy
#                     root GET    /                                         goals#index

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :goal
  validates :day_task_name, presence: true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
	  before_action :load_master_goal, :load_date_info, :check_goal_owner

  def index
    
    # sql select all the sub-weekly-goals -> input from the weekly view
    @given_week_sub_goals = @master_goal.weeks.where(week_num:@week, year:@year)

    # sql select all the daily tasks for give week -> input that was previously typed in This day view
    @week_day_tasks = @master_goal.days.where(week_num:@week, year:@year)

    # Creating the "framework" for displaying the @week_day_tasks on page (day_name + date provided)
    @days_array = []
    for i in 1..7 do
    	@days_array.push({day_name: Date::DAYNAMES[Date.commercial(@year,@week,i).wday], date: Date.commercial(@year,@week,i)})
    end

    # Creating variables for < > selection of the week, making sure that there is 1 last week of given year
    @next_week = next_week(@week, @year)
    @previous_week = previous_week(@week, @year)
  end

  def new
  	@day = params[:day]
  end

  def create
	  @day = params[:day].to_i
    @new_day_task = @master_goal.days.new(year: @year, month: @month, week_num: Date.new(@year,@month,@day).strftime("%V").to_i, day:@day, day_task_name: params[:new_day_task])
    if @new_day_task.save
      redirect_to goal_days_path(@master_goal,week:@week,year:params[:year]), notice: 'Day Task was created'
    else
      redirect_to goal_days_path(@master_goal,week:@week,year:params[:year]), notice: 'Try again! Day Task was NOT created'
    end
  end

  def edit
    @task = Day.find(params[:id])    
  end

  def update
    @task = Day.find(params[:id])
    @task.update(task_params)
    @week = (Date.new(@task[:year],@task[:month],@task[:day]).strftime("%V").to_i)
    @task.update(week_num:@week)
    redirect_to goal_days_path(@master_goal,week:@week)
  end

  def destroy
    @task = Day.find(params[:id])
    @task.destroy
    redirect_to goal_days_path(@master_goal,week:@week)
  end


  private
  def task_params
    params.require(:day).permit(:day_task_name, :day, :month, :year)
  end

  def load_master_goal
    @master_goal = Goal.find(params[:goal_id])
  end

  def load_date_info

    if params["year"] != nil
      @year = params["year"].to_i
    else
      @year = Date.today.year
    end  

    # handling special case when somebody changes the year in daily view on week 53 and another year has only 52wks
    if params["week"].to_i <= last_year_week_num(@year)
      if params["week"] != nil
        @week = params[:week].to_i
      else
        @week = Date.today.strftime("%V").to_i
      end
    else
      @week = last_year_week_num(@year)
    end

    @month = Date.commercial(@year,@week,4).month

  end

  def last_year_week_num(year)
    last_year_day = Date.new(year,12,31)
    if last_year_day.strftime("%V").to_i != 1
      return last_year_day.strftime("%V").to_i
    else
      return (last_year_day-7.days).strftime("%V").to_i
    end
  end

  def next_week(current_week,year)
    if current_week+1 <= last_year_week_num(year)
      return current_week+1
    else
      return 1
    end
  end

  def previous_week(current_week,year)
    if current_week-1 >= 1 
      return current_week-1
    else
      return last_year_week_num(year)
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/edit.html.erb
<% content_for :body_type do%>
  goalsedit
<% end %>

<div class="col-md-4 col-sm-4 col-xs-6 col-md-offset-4 col-sm-offset-4">
  <h3>Edit your goal</h3>
  <%= bootstrap_form_for([@master_goal, @task]) do |f| %>
    <%= label_tag(:day_task_name, "Current goal") %>
    <%= f.text_field :day_task_name, hide_label: true  %></br>
    <%= label_tag(:day, "Day") %>
    <%= f.text_field :day, hide_label: true  %></br>
    <%= label_tag(:month, "Month") %>
    <%= f.text_field :month, hide_label: true  %></br>
    <%= label_tag(:year, "Year") %>
    <%= f.text_field :year, hide_label: true  %></br>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <%end%>
  <%= link_to "Remove", goal_day_path(@master_goal, @task, week:@week), method: 'delete', :confirm => 'Are you sure?'%>
</div>

app/views/days/index.html.erb
<% content_for :body_type do%>
daysindex<% end %>

<%= link_to("#{Date::MONTHNAMES[@month]} overview", goal_weeks_path(@master_goal,month:@month, year:@year), class: "btn btn-primary") %>
<hr>
<h1 id="daysindexheader">Weekly Tasks for:</h1>
<div class="daynavi">
<%= link_to('<---', goal_days_path(@master_goal,week:@week,year:@year.to_i-1))%>
  <%=@year%>
<%= link_to('--->', goal_days_path(@master_goal,week:@week,year:@year.to_i+1))%>
<br>
<%= link_to('<---', goal_days_path(@master_goal,week:@previous_week,year:@year))%>
  Week: <%=@week%>
<%= link_to('--->', goal_days_path(@master_goal,week:@next_week,year:@year))%>
</div>
<hr>
<ul class="dayindexul">
  <% @given_week_sub_goals.each do |given_week_sub_goal| %>
    <li class="dayindexli">Weekly Goal: <%=given_week_sub_goal.weekly_goal_name%></li>
  <% end %>
</ul>
<hr>

<% @days_array.each do |day| %>
<table class="daystable" id="day_<%= day[:day_name] %>">
  <thead>
    <tr>
      <th><h3><%= "#{day[:date]}"%></h3> <h3><%= "#{day[:day_name]}"%></h3><h4><%= link_to("Create New Task", new_goal_day_path(@master_goal, week:@week, day:day[:date].day,year:@year)) %></h4></th>
    </tr>
  </thead>
  <tbody>
    <tr>
  <% if @week_day_tasks.where(day: day[:date].day, year: @year, week_num: @week) != nil %>
    <% @week_day_tasks.where(day: day[:date].day, year: @year, week_num: @week).each do |task| %>
      </tr>
      <tr>
      <td class="daytd"><%= task.day_task_name %> / 
      <%= link_to "Edit", edit_goal_day_path(@master_goal, task, week:@week)%></td> 
    <% end %>
  <% end %>
</tr>
</tbody>
</table>
  <hr>
<% end %>

app/views/days/new.html.erb
<% content_for :body_type do%>
daysnew<% end %>

<div class="daynewform">
<div class="form-group">
	<div class="col-md-6 col-sm-6 col-md-offset-1 col-sm-offset-1">

<form action="<%=goal_days_path(@master_goal,week:@week, year:@year, day:@day)%>" method="post">

  <%= token_tag form_authenticity_token %>
  <h1 id="daynewheader">New Daily Task:</h1><input type="text" placeholder="Go for a jog, etc." name="new_day_task" class="form-control" id="newdayform">
  <input type = "submit" id="daysubmit">
</form>
</div>
</div>
</div>