config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :goals do
    resources :months
    resources :weeks
	resources :days
  end

  root 'goals#index'

end

# Peters-MacBook-Pro:MeDoo petervarga$ rake routes
#                   Prefix Verb   URI Pattern                               Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                  devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                  devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                 devise/sessions#destroy
#            user_password POST   /users/password(.:format)                 devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)             devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)            devise/passwords#edit
#                          PATCH  /users/password(.:format)                 devise/passwords#update
#                          PUT    /users/password(.:format)                 devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                   devise/registrations#cancel
#        user_registration POST   /users(.:format)                          devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                  devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                     devise/registrations#edit
#                          PATCH  /users(.:format)                          devise/registrations#update
#                          PUT    /users(.:format)                          devise/registrations#update
#                          DELETE /users(.:format)                          devise/registrations#destroy
#              goal_months GET    /goals/:goal_id/months(.:format)          months#index
#                          POST   /goals/:goal_id/months(.:format)          months#create
#           new_goal_month GET    /goals/:goal_id/months/new(.:format)      months#new
#          edit_goal_month GET    /goals/:goal_id/months/:id/edit(.:format) months#edit
#               goal_month GET    /goals/:goal_id/months/:id(.:format)      months#show
#                          PATCH  /goals/:goal_id/months/:id(.:format)      months#update
#                          PUT    /goals/:goal_id/months/:id(.:format)      months#update
#                          DELETE /goals/:goal_id/months/:id(.:format)      months#destroy
#               goal_weeks GET    /goals/:goal_id/weeks(.:format)           weeks#index
#                          POST   /goals/:goal_id/weeks(.:format)           weeks#create
#            new_goal_week GET    /goals/:goal_id/weeks/new(.:format)       weeks#new
#           edit_goal_week GET    /goals/:goal_id/weeks/:id/edit(.:format)  weeks#edit
#                goal_week GET    /goals/:goal_id/weeks/:id(.:format)       weeks#show
#                          PATCH  /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          PUT    /goals/:goal_id/weeks/:id(.:format)       weeks#update
#                          DELETE /goals/:goal_id/weeks/:id(.:format)       weeks#destroy
#                goal_days GET    /goals/:goal_id/days(.:format)            days#index
#                          POST   /goals/:goal_id/days(.:format)            days#create
#             new_goal_day GET    /goals/:goal_id/days/new(.:format)        days#new
#            edit_goal_day GET    /goals/:goal_id/days/:id/edit(.:format)   days#edit
#                 goal_day GET    /goals/:goal_id/days/:id(.:format)        days#show
#                          PATCH  /goals/:goal_id/days/:id(.:format)        days#update
#                          PUT    /goals/:goal_id/days/:id(.:format)        days#update
#                          DELETE /goals/:goal_id/days/:id(.:format)        days#destroy
#                    goals GET    /goals(.:format)                          goals#index
#                          POST   /goals(.:format)                          goals#create
#                 new_goal GET    /goals/new(.:format)                      goals#new
#                edit_goal GET    /goals/:id/edit(.:format)                 goals#edit
#                     goal GET    /goals/:id(.:format)                      goals#show
#                          PATCH  /goals/:id(.:format)                      goals#update
#                          PUT    /goals/:id(.:format)                      goals#update
#                          DELETE /goals/:id(.:format)                      goals#destroy
#                     root GET    /                                         goals#index

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, presence: true
  has_many :months
  has_many :weeks
  has_many :days
  belongs_to :user

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :check_goal_owner, except: [:index, :new, :create]

  def index
    @goals = current_user.goals
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal= current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goals_path
    else
      flash[:error] = "Your Goal was not saved. Try again"
      redirect_to new_goal_path
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    redirect_to goals_path
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_path
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :description)
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
<% content_for :body_type do%>
goalsedit<% end %>

<h3 id="editgoalheader">Edit your goal</h3>

<div class="editgoalform">
	<div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-2 col-sm-offset-2">
		<%= bootstrap_form_for @goal do |f| %>

		<%= f.text_field :name  %></br>
	
		<%= f.text_area :description %></br>
		<div id="editgoalsubmit">
		<%= f.submit "Update", class: "btn btn-primary" %>
		</div>
	</div>
		<%end%>
</div>

app/views/goals/index.html.erb
<% content_for :body_type do%>
goalsindex<% end %>

<div id="creategoal"><%= link_to " + Create New Goal", new_goal_path, class: "btn btn-primary" %>
</div>

<div class="stickynotes">
<% @goals.each do |goal| %>
<ul class="indexul">
  <li class="indexli" id="goal_<%= goal.id%>">
      <h2 class="stickyheader">Goal: <%= link_to(goal.name, goal_months_path(goal) )%></h2>
      <p class="sticky">Details: <%= goal.description %></p>
      <p class="sticky">
        <%= link_to "Edit", edit_goal_path(goal.id)%>/<span><%= link_to("Remove", goal_path(goal.id,goal_id:goal.id), method: 'delete', :confirm => 'Are you sure?')%></span></p>
  </li>
</ul>
<% end %>
</div>

app/views/goals/month.html.erb
<h2>Months View</h2>

var montharray=new Array("January","February","March","April","May","June", "July","August","September","October","November","December")




<!-- Should pass in the name and description of the new goal form the new page. 

it will Display all 12 months.

Will have an edit button to add objectives for the month as well as link to weeks fo rhte month -->

app/views/goals/new.html.erb
<% content_for :body_type do%>
goalsnew<% end %>
<div class="newgoalhead">
<h1>My New Goal ~</h1>
</div>
<div class="newform">
<%= form_for @goal do |f| %>
<div id="newname">
<%= label_tag(:name, "Name your Goal!")%>
<%= f.text_field :name , :autofocus => true%></div></br>
<div id="newdescription">
<%= label_tag(:description, 'Description')%>
<%= f.text_field :description %></dev></br>
</div>
<div class="newcreate">
<%= f.submit "Create", class: "btn btn-link" %>
</div>
<%end%>